OPHJOD-2747: Add translations analyzation

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -20,5 +20,6 @@ for COMMIT in $NEW_COMMITS; do
   fi
 done
 
+npm run translations:check || (echo '\n (⊙＿⊙) Translation check failed! Fix dynamic keys, missing or unused translations.\n'; false)
 npm run test:unit || (echo '\n (⊙＿⊙) Your forgot to run unit tests!\n'; false)
 npm run build || (echo '\n (⊙＿⊙) Your forgot to run build!\n'; false)
